### ISSUE TITLE
Correct the order of room display

### ISSUE THREAD

**Issue by exSOUL** [kufu/mie#110]
### Issue
Currently, the order in which the seminar halls (e.g. Large Hall, Small Hall, Open Studio) are displayed on the application is inconsistent. This can cause confusion for the users and hinder understanding.

### Expected Behavior
The seminar halls should be displayed consistently according to their size.

### Proposed Solution
Let's correct the order of the halls so that the application displays them in the order of Large Hall → Medium Hall → Small Hall.

--- 

### 課題
現状、アプリケーション上で表示されるセミナーホール（e.g. 大ホール、中ホール、小ホール）の並び順が一貫性を持っていません。これはユーザーに混乱を与え、理解を妨げる可能性があります。

### 期待する挙動
セミナーホールは、その規模に応じて（大ホール、中ホール、小ホールの順に）一貫性を持って表示されるべきです。

### 提案される解決策
ホールの並び順を修正し、アプリケーションがホールを大ホール→中ホール→小ホールの順に表示する

**Comment by kinoppyd** [comment]
#128
